In [42]:
import numpy as np

x=np.array([1,2,3,4,5])
y=np.array([11,21,31,41,51])
print(x)
probe = np.zeros([5,5])
y.transpose()
print(y)
y1 = np.full_like(probe, y)
x1 = np.full_like(probe, x)
x1[1].transpose()
print(y)

[1 2 3 4 5]
[11 21 31 41 51]
[11 21 31 41 51]
